/**
 * API request and response type definitions
 * Corresponds to the backend API specification
 */

import type {
  BuildingConfig,
  BuildingType,
  GameConfig,
  InitialConfig,
  MapConfig,
  MonsterDisplayConfig,
  MonsterTypeId,
  Position,
} from './config'

// Re-export common types
export type {
  BuildingConfig,
  BuildingType,
  GameConfig,
  InitialConfig,
  MapConfig,
  MonsterDisplayConfig,
  MonsterTypeId,
  Position,
}

// ============================================================================
// POST /api/game/sessions - Create game session
// ============================================================================

/** Create session response */
export interface GameStartResponse {
  sessionId: string
  config: GameConfig
  firstWave: WaveConfig
}

/** Wave configuration */
export interface WaveConfig {
  waveNumber: number
  monsters: MonsterConfig[]
}

/** Single monster configuration (attributes computed by the server) */
export interface MonsterConfig {
  /** Monster unique ID (UUID generated by the server) */
  id: string
  /** Monster type (0-8) */
  type: MonsterTypeId
  /** Hit points (affected by difficulty modifier) */
  life: number
  /** Movement speed (affected by difficulty modifier) */
  speed: number
  /** Shield value (affected by difficulty modifier) */
  shield: number
  /** Money reward on kill */
  money: number
}

// ============================================================================
// POST /api/game/sessions/wave - Submit wave result
// ============================================================================

/** Wave submission request */
export interface WaveRequest {
  sessionId: string
  waveNumber: number
  actions: Action[]
  attacks: AttackEvent[]
  result: WaveResult
  buildings: BuildingSnapshot[]
}

/** Building action type */
export type ActionType = 'BUILD' | 'UPGRADE' | 'SELL'

/** Building action record */
export interface Action {
  type: ActionType
  /** Frame number when the action occurred */
  frame: number
  /** Building unique ID */
  buildingId: string
  /** Building type (for BUILD actions) */
  buildingType?: BuildingType
  /** Position (for BUILD actions) */
  position?: Position
  /** Level after upgrade (for UPGRADE actions) */
  level?: number
}

/** Attack event record */
export interface AttackEvent {
  /** Frame number when the hit occurred */
  frame: number
  /** ID of the building that initiated the attack */
  buildingId: string

  /** Monster ID targeted at the time of firing (used to verify the building had a valid target) */
  originalTargetId: string
  /** Grid coordinates of the target at the time of firing (used for range verification) */
  originalTargetPosition: Position

  /** Monster ID actually hit, may differ from originalTargetId ("friendly fire") */
  monsterId: string
  /** Grid coordinates of the monster when hit (used for path verification) */
  monsterPosition: Position

  /** Actual damage = max(rawDamage - shield, rawDamage x 0.1) */
  damage: number
}

/** Wave combat result */
export interface WaveResult {
  /** Total monsters killed */
  killed: number
  /** Kills by monster type (only includes types present in this wave) */
  killedByType: Partial<Record<MonsterTypeId, number>>
  /** Number of monsters that passed through the exit */
  passed: number
  /** Remaining monsters on the field when ending early (optional, default 0) */
  remaining?: number
  /** IDs of remaining monsters on the field when ending early (optional) */
  remainingMonsterIds?: string[]
  /** Actual number of monsters spawned this wave (optional, defaults to wave config total) */
  spawned?: number
  /** Score gained */
  scoreGained: number
  /** Money gained */
  moneyGained: number
  /** Life lost */
  lifeLost: number
  /** Total damage dealt */
  totalDamageDealt: number
  /** Total life of killed monsters */
  totalLifeDestroyed: number
  /** Wave duration in frames */
  waveDurationFrames: number
}

/** Building state snapshot */
export interface BuildingSnapshot {
  id: string
  type: BuildingType
  position: Position
  level: number
  /** Damage dealt this wave */
  damageDealt: number
  /** Kills this wave */
  kills: number
}

/** Wave submission response */
export interface WaveResponse {
  valid: boolean
  /** Server-computed state (for synchronization) */
  serverState: ServerState
  /** Next wave configuration (returned when the game continues) */
  nextWave?: WaveConfig & {
    /** Life recovery reward */
    lifeReward?: number
  }
  /** Returned on validation failure */
  error?: ApiError
}

/** Server state (for synchronization) */
export interface ServerState {
  money: number
  score: number
  life: number
  difficulty: number
}

// ============================================================================
// POST /api/game/sessions/end - Game over
// ============================================================================

/** Game end request */
export interface GameEndRequest {
  sessionId: string
  nickname: string
  /** Last wave data (optional, not provided when ending early) */
  lastWave?: {
    waveNumber: number
    actions: Action[]
    attacks: AttackEvent[]
    result: WaveResult
    buildings: BuildingSnapshot[]
  }
}

/** Game end response */
export interface GameEndResponse {
  verified: boolean
  /** Ranking information */
  ranking?: RankingInfo
  /** Returned on validation failure */
  error?: ApiError
}

/** Ranking information */
export interface RankingInfo {
  /** Current rank */
  rank: number
  /** Total participants */
  total: number
  /** Whether a new record was set */
  isNewRecord: boolean
}

// ============================================================================
// GET /api/game/leaderboard - Leaderboard
// ============================================================================

/** Leaderboard response */
export interface LeaderboardResponse {
  entries: LeaderboardEntry[]
}

/** Leaderboard entry */
export interface LeaderboardEntry {
  /** Rank (starting from 1) */
  rank: number
  /** Player nickname */
  nickname: string
  /** Final score */
  score: number
  /** Number of waves completed */
  wavesCompleted: number
  /** Record time (ISO 8601) */
  createdAt: string
}

// ============================================================================
// Common types
// ============================================================================

/** API error */
export interface ApiError {
  code: ApiErrorCode
  message: string
}

/** Error code enum */
export type ApiErrorCode =
  | 'SESSION_NOT_FOUND'
  | 'VALIDATION_FAILED'
  | 'INVALID_REQUEST'
