# Generated by Django 6.0 on 2026-01-04 07:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GameSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("money", models.IntegerField(help_text="当前金钱")),
                ("score", models.IntegerField(default=0, help_text="累计分数")),
                ("life", models.IntegerField(help_text="当前生命值")),
                (
                    "wave_count",
                    models.IntegerField(default=0, help_text="已完成的波次数"),
                ),
                (
                    "difficulty",
                    models.FloatField(default=1.0, help_text="当前难度系数"),
                ),
                ("buildings", models.JSONField(default=list, help_text="当前建筑列表")),
                (
                    "config",
                    models.JSONField(help_text="游戏配置（建筑、怪物、地图等）"),
                ),
                ("next_wave", models.JSONField(help_text="下一波怪物配置")),
            ],
            options={
                "db_table": "game_session",
                "indexes": [
                    models.Index(
                        fields=["created_at"], name="game_sessio_created_010a58_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="LeaderboardEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nickname", models.CharField(help_text="玩家昵称", max_length=32)),
                ("score", models.IntegerField(help_text="最终得分")),
                ("waves_completed", models.IntegerField(help_text="完成的波次数")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "leaderboard",
                "ordering": ["-score", "-waves_completed"],
                "indexes": [
                    models.Index(
                        fields=["-score"], name="leaderboard_score_10f103_idx"
                    ),
                    models.Index(
                        fields=["-score", "-waves_completed"],
                        name="leaderboard_score_ffb45f_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="WaveRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("wave_number", models.IntegerField(help_text="波次编号（从 1 开始）")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("killed", models.IntegerField(help_text="击杀怪物数")),
                (
                    "killed_by_type",
                    models.JSONField(
                        default=dict, help_text="每种怪物类型的击杀数 {type_id: count}"
                    ),
                ),
                ("passed", models.IntegerField(help_text="穿过终点的怪物数")),
                ("score_gained", models.IntegerField(help_text="本波获得的分数")),
                ("money_gained", models.IntegerField(help_text="本波获得的金钱")),
                ("life_lost", models.IntegerField(help_text="本波损失的生命值")),
                (
                    "total_damage_dealt",
                    models.IntegerField(help_text="本波造成的总伤害"),
                ),
                (
                    "total_life_destroyed",
                    models.IntegerField(default=0, help_text="击杀怪物的总生命值"),
                ),
                ("wave_duration_frames", models.IntegerField(help_text="波次持续帧数")),
                ("money_spent", models.IntegerField(help_text="本波花费的金钱")),
                ("money_income", models.IntegerField(help_text="本波出售建筑的收入")),
                (
                    "building_count",
                    models.IntegerField(help_text="波次结束时的建筑数量"),
                ),
                ("end_money", models.IntegerField(help_text="波次结束时的金钱")),
                ("end_score", models.IntegerField(help_text="波次结束时的分数")),
                ("end_life", models.IntegerField(help_text="波次结束时的生命值")),
                ("end_difficulty", models.FloatField(help_text="波次结束时的难度系数")),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="waves",
                        to="game.gamesession",
                    ),
                ),
            ],
            options={
                "db_table": "wave_record",
                "ordering": ["wave_number"],
                "indexes": [
                    models.Index(
                        fields=["session", "wave_number"],
                        name="wave_record_session_cde669_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("session", "wave_number"), name="unique_session_wave"
                    )
                ],
            },
        ),
    ]
