# Generated by Django 6.0 on 2026-01-04 07:10

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GameSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("money", models.IntegerField(help_text="Current money")),
                (
                    "score",
                    models.IntegerField(
                        default=0, help_text="Cumulative score"
                    ),
                ),
                ("life", models.IntegerField(help_text="Current life points")),
                (
                    "wave_count",
                    models.IntegerField(
                        default=0, help_text="Completed wave count"
                    ),
                ),
                (
                    "difficulty",
                    models.FloatField(
                        default=1.0, help_text="Current difficulty multiplier"
                    ),
                ),
                (
                    "buildings",
                    models.JSONField(default=list, help_text="Current building list"),
                ),
                (
                    "config",
                    models.JSONField(
                        help_text="Game config (buildings, monsters, map, etc.)"
                    ),
                ),
                (
                    "next_wave",
                    models.JSONField(help_text="Next wave monster config"),
                ),
            ],
            options={
                "db_table": "game_session",
                "indexes": [
                    models.Index(
                        fields=["created_at"], name="game_sessio_created_010a58_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="LeaderboardEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "nickname",
                    models.CharField(help_text="Player nickname", max_length=32),
                ),
                ("score", models.IntegerField(help_text="Final score")),
                (
                    "waves_completed",
                    models.IntegerField(help_text="Waves completed"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "leaderboard",
                "ordering": ["-score", "-waves_completed"],
                "indexes": [
                    models.Index(
                        fields=["-score"], name="leaderboard_score_10f103_idx"
                    ),
                    models.Index(
                        fields=["-score", "-waves_completed"],
                        name="leaderboard_score_ffb45f_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="WaveRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "wave_number",
                    models.IntegerField(
                        help_text="Wave number (starting from 1)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "killed",
                    models.IntegerField(help_text="Monsters killed"),
                ),
                (
                    "killed_by_type",
                    models.JSONField(
                        default=dict,
                        help_text="Kills per monster type {type_id: count}",
                    ),
                ),
                (
                    "passed",
                    models.IntegerField(
                        help_text="Monsters that reached the end"
                    ),
                ),
                (
                    "score_gained",
                    models.IntegerField(help_text="Score gained this wave"),
                ),
                (
                    "money_gained",
                    models.IntegerField(help_text="Money gained this wave"),
                ),
                (
                    "life_lost",
                    models.IntegerField(help_text="Life lost this wave"),
                ),
                (
                    "total_damage_dealt",
                    models.IntegerField(
                        help_text="Total damage dealt this wave"
                    ),
                ),
                (
                    "total_life_destroyed",
                    models.IntegerField(
                        default=0,
                        help_text="Total HP of killed monsters",
                    ),
                ),
                (
                    "wave_duration_frames",
                    models.IntegerField(help_text="Wave duration in frames"),
                ),
                (
                    "money_spent",
                    models.IntegerField(help_text="Money spent this wave"),
                ),
                (
                    "money_income",
                    models.IntegerField(
                        help_text="Income from selling buildings this wave"
                    ),
                ),
                (
                    "building_count",
                    models.IntegerField(
                        help_text="Building count at wave end"
                    ),
                ),
                (
                    "end_money",
                    models.IntegerField(help_text="Money at wave end"),
                ),
                (
                    "end_score",
                    models.IntegerField(help_text="Score at wave end"),
                ),
                (
                    "end_life",
                    models.IntegerField(help_text="Life at wave end"),
                ),
                (
                    "end_difficulty",
                    models.FloatField(
                        help_text="Difficulty multiplier at wave end"
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="waves",
                        to="game.gamesession",
                    ),
                ),
            ],
            options={
                "db_table": "wave_record",
                "ordering": ["wave_number"],
                "indexes": [
                    models.Index(
                        fields=["session", "wave_number"],
                        name="wave_record_session_cde669_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("session", "wave_number"), name="unique_session_wave"
                    )
                ],
            },
        ),
    ]
