# Generated by Django 6.0 on 2026-01-06 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="waverecord",
            name="remaining",
            field=models.IntegerField(
                default=0, help_text="Monsters remaining on early end"
            ),
        ),
    ]
